### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by ralin3** [gerard33/frontpage#1]
Hi,
Would it be possible to translate frontpage_settings.js to english?
As it is now, it's hard to use this when you dont understand dutch.

**Comment by gerard33** [comment]
Most of the Dutch texts in frontpage_settings are shown on my frontpage, so I leave them Dutch.
I understand that is easier to understand when all texts are in English, but in that case [Google Translate](https://translate.google.nl/#nl/en/!--%20Change%20the%20text%20for%20on%2Foff%20switches%20--%3E%0A%3C!--%20var%20txt_on%20%3D%20'%3Cimg%20src%3Dicons%2Fon.png%3E'%3B%20--%3E%0A%3C!--%20var%20txt_off%20%3D%20'%3Cimg%20src%3Dicons%2Foff.png%3E'%3B%20--%3E%0Avar%20txt_on%20%3D%20'Aan'%3B%0Avar%20txt_off%20%3D%20'Uit'%3B%0Avar%20txt_zonon%20%3D%20'Uit'%3B%20%3C!--%20Dicht%20--%3E%0Avar%20txt_zonoff%20%3D%20'In'%3B%20%3C!--%20Open%20--%3E%0Avar%20txt_zonstopped%20%3D%20'Gestopt'%3B%0Avar%20txt_zonstop%20%3D%20'%7C%20%7C'%3B%0A%3C!--%20var%20txt_dim_plus%20%3D%20'%20%2B%20'%3B%20--%3E%0A%3C!--%20var%20txt_dim_min%20%3D%20'%20-%20'%3B%20--%3E%0A%0A%3C!--%20Change%20the%20text%20displayed%20in%20PopUps%20--%3E%0Avar%20txt_switch_protected%20%3D%20'%5C'Schakelaar%20is%20beveiligd%5C''%3B%0Avar%20txt_switch_on%20%3D%20'%5C'Inschakelen%5C''%3B%0Avar%20txt_switch_off%20%3D%20'%5C'Uitschakelen%5C''%3B%0Avar%20txt_blind_up%20%3D%20'%5C'Zonnescherm%20uit%5C''%3B%0Avar%20txt_blind_down%20%3D%20'%5C'Zonnescherm%20in%5C''%3B%0Avar%20txt_blind_stop%20%3D%20'%5C'Zonnescherm%20stoppen%5C''%3B) could be handy.
